"use client";

export const dStats = [
  {
    team: "Miami Vice",
    player: "Andrew Gonzo",
    sacks: 2,
    tackles: 7,
    picks: 1,
  },
  {
    team: "Miami Vice",
    player: "Anthony Perlongo",
    sacks: 3,
    tackles: 22,
    picks: 7,
  },
  {
    team: "Blue Ballers",
    player: "Josh Soler",
    sacks: 7,
    tackles: 17,
    picks: 0,
  },
  {
    team: "The Clan",
    player: "Matt Rossi",
    sacks: 0,
    tackles: 2,
    picks: 1,
  },
  {
    team: "Bomb Squad",
    player: "Edin Hernandez",
    sacks: 1,
    tackles: 25,
    picks: 1,
  },
  {
    team: "Bulls",
    player: "Ross",
    sacks: 2,
    tackles: 20,
    picks: 2,
  },
  {
    team: "Bulls",
    player: "Kevin Wu",
    sacks: 0,
    tackles: 29,
    picks: 1,
  },
  {
    team: "Bomb Squad",
    player: "Justin Kotowitz",
    sacks: 0,
    tackles: 11,
    picks: 2,
  },
  {
    team: "Redskins",
    player: "Sergio Rigau",
    sacks: 0,
    tackles: 16,
    picks: 5,
  },
  {
    team: "Blue Ballers",
    player: "Danny Gonzo",
    sacks: 0,
    tackles: 9,
    picks: 8,
  },
  {
    team: "The Clan",
    player: "Nick Venditti",
    sacks: 0,
    tackles: 27,
    picks: 0,
  },
  {
    team: "Redskins",
    player: "Christian Dedato",
    sacks: 0,
    tackles: 18,
    picks: 1,
  },
  {
    team: "Redskins",
    player: "Mark Ortega",
    sacks: 0,
    tackles: 25,
    picks: 1,
  },
  {
    team: "The Clan",
    player: "Mike Decanio",
    sacks: 0,
    tackles: 3,
    picks: 1,
  },
  {
    team: "Bomb Squad",
    player: "Nick Talledo",
    sacks: 0,
    tackles: 15,
    picks: 1,
  },
  {
    team: "The Clan",
    player: "Andrew Rossi",
    sacks: 4,
    tackles: 8,
    picks: 3,
  },
  {
    team: "Blue Ballers",
    player: "Andrew Aspromonte",
    sacks: 0,
    tackles: 9,
    picks: 0,
  },
  {
    team: "Bulls",
    player: "Devin",
    sacks: 0,
    tackles: 13,
    picks: 3,
  },
  {
    team: "Bulls",
    player: "Ryan",
    sacks: 0,
    tackles: 24,
    picks: 3,
  },
  {
    team: "Bomb Squad",
    player: "Jared Kerman",
    sacks: 1,
    tackles: 9,
    picks: 1,
  },
  {
    team: "Miami Vice",
    player: "Adrian Rugova",
    sacks: 6,
    tackles: 3,
    picks: 0,
  },
  {
    team: "Blue Ballers",
    player: "Dean",
    sacks: 0,
    tackles: 11,
    picks: 1,
  },
  {
    team: "Miami Vice",
    player: "Vincent Nastri",
    sacks: 0,
    tackles: 16,
    picks: 0,
  },
  {
    team: "Redskins",
    player: "Chazz",
    sacks: 2,
    tackles: 1,
    picks: 0,
  },
  {
    team: "Miami Vice",
    player: "Nico",
    sacks: 0,
    tackles: 10,
    picks: 0,
  },
  {
    team: "Redskins",
    player: "Deni K",
    sacks: 0,
    tackles: 0,
    picks: 0,
  },
  {
    team: "Blue Ballers",
    player: "Tom Mauro",
    sacks: 0,
    tackles: 0,
    picks: 0,
  },
  {
    team: "The Clan",
    player: "CJ",
    sacks: 3,
    tackles: 6,
    picks: 0,
  },
  {
    team: "Bomb Squad",
    player: "Charles",
    sacks: 0,
    tackles: 6,
    picks: 0,
  },
  {
    team: "Bulls",
    player: "Klevik",
    sacks: 0,
    tackles: 6,
    picks: 0,
  },
  {
    team: "Redskins",
    player: "Jonny",
    sacks: 0,
    tackles: 13,
    picks: 1,
  },
  {
    team: "Miami Vice",
    player: "Nick Cupelli",
    sacks: 0,
    tackles: 33,
    picks: 1,
  },
  {
    team: "Blue Ballers",
    player: "Nicky",
    sacks: 0,
    tackles: 18,
    picks: 2,
  },
  {
    team: "The Clan",
    player: "Nick Dinicola",
    sacks: 0,
    tackles: 37,
    picks: 5,
  },
  {
    team: "Bomb Squad",
    player: "Stephen Aspromonte",
    sacks: 0,
    tackles: 28,
    picks: 0,
  },
  {
    team: "Bulls",
    player: "Redbull",
    sacks: 1,
    tackles: 12,
    picks: 5,
  },
  {
    team: "Blue Ballers",
    player: "Jack",
    sacks: 0,
    tackles: 6,
    picks: 1,
  },
];
