"use client";

export const oStats = [
  {
    team: "Miami Vice",
    player: "Andrew Gonzo",
    receptions: 40,
    yards: 604,
    touchdowns: 12,
  },
  {
    team: "Miami Vice",
    player: "Anthony Perlongo",
    receptions: 46,
    yards: 730,
    touchdowns: 17,
  },
  {
    team: "Bomb Squad",
    player: "Josh Soler",
    receptions: 49,
    yards: 482,
    touchdowns: 10,
  },
  {
    team: "The Clan",
    player: "Matt Rossi",
    receptions: 38,
    yards: 523,
    touchdowns: 12,
  },
  {
    team: "Bomb Squad",
    player: "Edin Hernandez",
    receptions: 72,
    yards: 768,
    touchdowns: 11,
  },
  {
    team: "Bulls",
    player: "Ross",
    receptions: 58,
    yards: 685,
    touchdowns: 18,
  },
  {
    team: "Bulls",
    player: "Kevin Wu",
    receptions: 16,
    yards: 209,
    touchdowns: 7,
  },
  {
    team: "Blue Ballers",
    player: "Justin Kotowitz",
    receptions: 45,
    yards: 562,
    touchdowns: 11,
  },
  {
    team: "Redskins",
    player: "Sergio Rigau",
    receptions: 25,
    yards: 326,
    touchdowns: 7,
  },
  {
    team: "Blue Ballers",
    player: "Danny Gonzo",
    receptions: 68,
    yards: 625,
    touchdowns: 13,
  },
  {
    team: "The Clan",
    player: "Nick Venditti",
    receptions: 61,
    yards: 652,
    touchdowns: 9,
  },
  {
    team: "Redskins",
    player: "Christian Dedato",
    receptions: 32,
    yards: 456,
    touchdowns: 6,
  },
  {
    team: "Redskins",
    player: "Mark",
    receptions: 16,
    yards: 218,
    touchdowns: 4,
  },
  {
    team: "The Clan",
    player: "Mike Decanio",
    receptions: 4,
    yards: 24,
    touchdowns: 2,
  },
  {
    team: "Bomb Squad",
    player: "Nick Talledo",
    receptions: 29,
    yards: 412,
    touchdowns: 7,
  },
  {
    team: "The Clan",
    player: "Andrew Rossi",
    receptions: 20,
    yards: 211,
    touchdowns: 5,
  },
  {
    team: "Blue Ballers",
    player: "Andrew Aspromonte",
    receptions: 11,
    yards: 142,
    touchdowns: 2,
  },
  {
    team: "Bulls",
    player: "Devin",
    receptions: 6,
    yards: 76,
    touchdowns: 4,
  },
  {
    team: "Bulls",
    player: "Ryan",
    receptions: 17,
    yards: 278,
    touchdowns: 5,
  },
  {
    team: "Bomb Squad",
    player: "Jared",
    receptions: 6,
    yards: 134,
    touchdowns: 2,
  },
  {
    team: "Blue Ballers",
    player: "Adrian",
    receptions: 11,
    yards: 139,
    touchdowns: 2,
  },
  {
    team: "Miami Vice",
    player: "Dean",
    receptions: 21,
    yards: 279,
    touchdowns: 3,
  },
  {
    team: "Miami Vice",
    player: "Vincent Nastri",
    receptions: 26,
    yards: 390,
    touchdowns: 9,
  },
  {
    team: "Redskins",
    player: "Chazz",
    receptions: 21,
    yards: 169,
    touchdowns: 5,
  },
  {
    team: "Miami Vice",
    player: "Nico",
    receptions: 42,
    yards: 362,
    touchdowns: 6,
  },
  {
    team: "Redskins",
    player: "Deni K",
    receptions: 3,
    yards: 60,
    touchdowns: 2,
  },
  {
    team: "Blue Ballers",
    player: "Tom Mauro",
    receptions: 0,
    yards: 0,
    touchdowns: 0,
  },
  {
    team: "The Clan",
    player: "CJ",
    receptions: 2,
    yards: 11,
    touchdowns: 1,
  },
  {
    team: "Bomb Squad",
    player: "Charles",
    receptions: 2,
    yards: 22,
    touchdowns: 0,
  },
  {
    team: "Bulls",
    player: "Klevik",
    receptions: 30,
    yards: 335,
    touchdowns: 2,
  },
  {
    team: "Blue Ballers",
    player: "Jack",
    receptions: 10,
    yards: 89,
    touchdowns: 1,
  },
  {
    team: "Blue Ballers",
    player: "Nicky",
    receptions: 2,
    yards: 17,
    touchdowns: 0,
  },
  {
    team: "Miami Vice",
    player: "Nick Cupelli",
    receptions: 2,
    yards: 29,
    touchdowns: 2,
  },
];

// {
//   team: "Redskins",
//   player: "Jonny",
//   receptions: 0,
//   yards: 0,
//   touchdowns: 0,
// },
// {
//   team: "The Clan",
//   player: "Nick Dinicola",
//   receptions: 0,
//   yards: 0,
//   touchdowns: 0,
// },
// {
//   team: "Bomb Squad",
//   player: "Stephen",
//   receptions: 0,
//   yards: 0,
//   touchdowns: 0,
// },
// {
//   team: "Bulls",
//   player: "Redbull",
//   receptions: 0,
//   yards: 0,
//   touchdowns: 0,
// },
