"use client";

export const oStats = [
  {
    team: "Redskins",
    player: "Andrew Gonzo",
    receptions: 8,
    yards: 101,
    touchdowns: 3,
  },
  {
    team: "Miami Vice",
    player: "Anthony Perlongo",
    receptions: 5,
    yards: 74,
    touchdowns: 1,
  },
  {
    team: "Blue Ballers",
    player: "Josh Soler",
    receptions: 10,
    yards: 105,
    touchdowns: 2,
  },
  {
    team: "The Clan",
    player: "Matt Rossi",
    receptions: 11,
    yards: 184,
    touchdowns: 5,
  },
  {
    team: "Bomb Squad",
    player: "Edin Hernandez",
    receptions: 12,
    yards: 168,
    touchdowns: 1,
  },
  {
    team: "Bulls",
    player: "Ross",
    receptions: 14,
    yards: 88,
    touchdowns: 3,
  },
  {
    team: "Bulls",
    player: "Kevin Wu",
    receptions: 4,
    yards: 61,
    touchdowns: 1,
  },
  {
    team: "Bomb Squad",
    player: "Justin Kotowitz",
    receptions: 18,
    yards: 166,
    touchdowns: 4,
  },
  {
    team: "Miami Vice",
    player: "Sergio Rigau",
    receptions: 5,
    yards: 76,
    touchdowns: 0,
  },
  {
    team: "Blue Ballers",
    player: "Danny Gonzo",
    receptions: 14,
    yards: 136,
    touchdowns: 1,
  },
  {
    team: "The Clan",
    player: "Nick Venditti",
    receptions: 16,
    yards: 108,
    touchdowns: 0,
  },
  {
    team: "Redskins",
    player: "Christian Dedato",
    receptions: 6,
    yards: 111,
    touchdowns: 1,
  },
  {
    team: "Redskins",
    player: "Mark",
    receptions: 1,
    yards: 5,
    touchdowns: 0,
  },
  {
    team: "The Clan",
    player: "Mike Decanio",
    receptions: 0,
    yards: 0,
    touchdowns: 0,
  },
  {
    team: "Blue Ballers",
    player: "Nick Talledo",
    receptions: 7,
    yards: 73,
    touchdowns: 1,
  },
  {
    team: "The Clan",
    player: "Andrew Rossi",
    receptions: 4,
    yards: 44,
    touchdowns: 0,
  },
  {
    team: "Bomb Squad",
    player: "Andrew Aspromonte",
    receptions: 4,
    yards: 29,
    touchdowns: 0,
  },
  {
    team: "Bulls",
    player: "Devin",
    receptions: 0,
    yards: 0,
    touchdowns: 0,
  },
  {
    team: "Bulls",
    player: "Ryan",
    receptions: 7,
    yards: 73,
    touchdowns: 2,
  },
  {
    team: "Bomb Squad",
    player: "Jared",
    receptions: 0,
    yards: 0,
    touchdowns: 0,
  },
  {
    team: "Miami Vice",
    player: "Adrian",
    receptions: 6,
    yards: 63,
    touchdowns: 2,
  },
  {
    team: "Blue Ballers",
    player: "Dean",
    receptions: 6,
    yards: 97,
    touchdowns: 1,
  },
  {
    team: "Miami Vice",
    player: "Vincent Nastri",
    receptions: 3,
    yards: 40,
    touchdowns: 1,
  },
  {
    team: "Redskins",
    player: "Chazz",
    receptions: 13,
    yards: 83,
    touchdowns: 3,
  },
  {
    team: "Redskins",
    player: "Nico",
    receptions: 11,
    yards: 43,
    touchdowns: 3,
  },
  {
    team: "Miami Vice",
    player: "Deni K",
    receptions: 0,
    yards: 0,
    touchdowns: 0,
  },
  {
    team: "Blue Ballers",
    player: "Tom Mauro",
    receptions: 0,
    yards: 0,
    touchdowns: 0,
  },
  {
    team: "The Clan",
    player: "CJ",
    receptions: 0,
    yards: 0,
    touchdowns: 0,
  },
  {
    team: "Bomb Squad",
    player: "Charles",
    receptions: 0,
    yards: 0,
    touchdowns: 0,
  },
  {
    team: "Bulls",
    player: "Klevik",
    receptions: 6,
    yards: 45,
    touchdowns: 0,
  },
];

// {
//   team: "Redskins",
//   player: "Jonny",
//   receptions: 0,
//   yards: 0,
//   touchdowns: 0,
// },
// {
//   team: "Miami Vice",
//   player: "Nick Cupelli",
//   receptions: 0,
//   yards: 0,
//   touchdowns: 0,
// },
// {
//   team: "Blue Ballers",
//   player: "Nicky",
//   receptions: 0,
//   yards: 0,
//   touchdowns: 0,
// },
// {
//   team: "The Clan",
//   player: "Nick Dinicola",
//   receptions: 0,
//   yards: 0,
//   touchdowns: 0,
// },
// {
//   team: "Bomb Squad",
//   player: "Stephen",
//   receptions: 0,
//   yards: 0,
//   touchdowns: 0,
// },
// {
//   team: "Bulls",
//   player: "Redbull",
//   receptions: 0,
//   yards: 0,
//   touchdowns: 0,
// },
