"use client";

export const oStats = [
  {
    team: "Miami Vice",
    player: "Andrew Gonzo",
    receptions: 29,
    yards: 395,
    touchdowns: 9,
  },
  {
    team: "Miami Vice",
    player: "Anthony Perlongo",
    receptions: 28,
    yards: 460,
    touchdowns: 10,
  },
  {
    team: "Blue Ballers",
    player: "Josh Soler",
    receptions: 39,
    yards: 377,
    touchdowns: 8,
  },
  {
    team: "The Clan",
    player: "Matt Rossi",
    receptions: 17,
    yards: 317,
    touchdowns: 8,
  },
  {
    team: "Bomb Squad",
    player: "Edin Hernandez",
    receptions: 39,
    yards: 481,
    touchdowns: 6,
  },
  {
    team: "Bulls",
    player: "Ross",
    receptions: 45,
    yards: 512,
    touchdowns: 12,
  },
  {
    team: "Bulls",
    player: "Kevin Wu",
    receptions: 7,
    yards: 131,
    touchdowns: 4,
  },
  {
    team: "Bomb Squad",
    player: "Justin Kotowitz",
    receptions: 31,
    yards: 377,
    touchdowns: 9,
  },
  {
    team: "Redskins",
    player: "Sergio Rigau",
    receptions: 23,
    yards: 275,
    touchdowns: 6,
  },
  {
    team: "Blue Ballers",
    player: "Danny Gonzo",
    receptions: 44,
    yards: 373,
    touchdowns: 8,
  },
  {
    team: "The Clan",
    player: "Nick Venditti",
    receptions: 38,
    yards: 378,
    touchdowns: 3,
  },
  {
    team: "Redskins",
    player: "Christian Dedato",
    receptions: 28,
    yards: 399,
    touchdowns: 4,
  },
  {
    team: "Redskins",
    player: "Mark",
    receptions: 13,
    yards: 184,
    touchdowns: 4,
  },
  {
    team: "The Clan",
    player: "Mike Decanio",
    receptions: 4,
    yards: 24,
    touchdowns: 2,
  },
  {
    team: "Bomb Squad",
    player: "Nick Talledo",
    receptions: 18,
    yards: 278,
    touchdowns: 5,
  },
  {
    team: "The Clan",
    player: "Andrew Rossi",
    receptions: 17,
    yards: 182,
    touchdowns: 5,
  },
  {
    team: "Blue Ballers",
    player: "Andrew Aspromonte",
    receptions: 8,
    yards: 80,
    touchdowns: 1,
  },
  {
    team: "Bulls",
    player: "Devin",
    receptions: 2,
    yards: 20,
    touchdowns: 2,
  },
  {
    team: "Bulls",
    player: "Ryan",
    receptions: 13,
    yards: 201,
    touchdowns: 5,
  },
  {
    team: "Bomb Squad",
    player: "Jared",
    receptions: 2,
    yards: 25,
    touchdowns: 0,
  },
  {
    team: "Miami Vice",
    player: "Adrian",
    receptions: 11,
    yards: 139,
    touchdowns: 2,
  },
  {
    team: "Blue Ballers",
    player: "Dean",
    receptions: 11,
    yards: 160,
    touchdowns: 1,
  },
  {
    team: "Miami Vice",
    player: "Vincent Nastri",
    receptions: 17,
    yards: 273,
    touchdowns: 5,
  },
  {
    team: "Redskins",
    player: "Chazz",
    receptions: 13,
    yards: 83,
    touchdowns: 3,
  },
  {
    team: "Miami Vice",
    player: "Nico",
    receptions: 32,
    yards: 218,
    touchdowns: 3,
  },
  {
    team: "Redskins",
    player: "Deni K",
    receptions: 0,
    yards: 0,
    touchdowns: 0,
  },
  {
    team: "Blue Ballers",
    player: "Tom Mauro",
    receptions: 0,
    yards: 0,
    touchdowns: 0,
  },
  {
    team: "The Clan",
    player: "CJ",
    receptions: 0,
    yards: 0,
    touchdowns: 0,
  },
  {
    team: "Bomb Squad",
    player: "Charles",
    receptions: 2,
    yards: 22,
    touchdowns: 0,
  },
  {
    team: "Bulls",
    player: "Klevik",
    receptions: 24,
    yards: 265,
    touchdowns: 1,
  },
  {
    team: "Blue Ballers",
    player: "Jack",
    receptions: 10,
    yards: 89,
    touchdowns: 1,
  },
  {
    team: "Blue Ballers",
    player: "Nicky",
    receptions: 0,
    yards: 0,
    touchdowns: 0,
  },
  {
    team: "Miami Vice",
    player: "Nick Cupelli",
    receptions: 0,
    yards: 29,
    touchdowns: 1,
  },
];

// {
//   team: "Redskins",
//   player: "Jonny",
//   receptions: 0,
//   yards: 0,
//   touchdowns: 0,
// },
// {
//   team: "The Clan",
//   player: "Nick Dinicola",
//   receptions: 0,
//   yards: 0,
//   touchdowns: 0,
// },
// {
//   team: "Bomb Squad",
//   player: "Stephen",
//   receptions: 0,
//   yards: 0,
//   touchdowns: 0,
// },
// {
//   team: "Bulls",
//   player: "Redbull",
//   receptions: 0,
//   yards: 0,
//   touchdowns: 0,
// },
