"use client";

export const qbStats = [
  {
    team: "Redskins",
    player: "Jonny",
    completions: 100,
    Ryards: 114,
    Pyards: 1088,
    picks: 6,
    Rtouchdowns: 3,
    Ptouchdowns: 23,
  },
  {
    team: "Miami Vice",
    player: "Nick Cupelli",
    completions: 69,
    Ryards: 145,
    Pyards: 767,
    picks: 1,
    Rtouchdowns: 3,
    Ptouchdowns: 15,
  },
  {
    team: "Blue Ballers",
    player: "Nicky",
    completions: 107,
    Ryards: 131,
    Pyards: 1069,
    picks: 3,
    Rtouchdowns: 0,
    Ptouchdowns: 15,
  },
  {
    team: "The Clan",
    player: "Nick Dinicola",
    completions: 62,
    Ryards: 216,
    Pyards: 707,
    picks: 4,
    Rtouchdowns: 3,
    Ptouchdowns: 13,
  },
  {
    team: "Bomb Squad",
    player: "Stephen",
    completions: 84,
    Ryards: 122,
    Pyards: 1107,
    picks: 6,
    Rtouchdowns: 3,
    Ptouchdowns: 20,
  },
  {
    team: "Bulls",
    player: "Redbull",
    completions: 76,
    Ryards: 253,
    Pyards: 771,
    picks: 5,
    Rtouchdowns: 6,
    Ptouchdowns: 18,
  },
];
