"use client";

export const qbStats = [
  {
    team: "Redskins",
    player: "Jonny",
    completions: 176,
    Ryards: 406,
    Pyards: 2073,
    picks: 17,
    Rtouchdowns: 8,
    Ptouchdowns: 40,
  },
  {
    team: "Miami Vice",
    player: "Nick Cupelli",
    completions: 204,
    Ryards: 373,
    Pyards: 2671,
    picks: 12,
    Rtouchdowns: 9,
    Ptouchdowns: 48,
  },
  {
    team: "Blue Ballers",
    player: "Nicky",
    completions: 164,
    Ryards: 186,
    Pyards: 1706,
    picks: 12,
    Rtouchdowns: 0,
    Ptouchdowns: 27,
  },
  {
    team: "The Clan",
    player: "Nick Dinicola",
    completions: 175,
    Ryards: 490,
    Pyards: 2307,
    picks: 10,
    Rtouchdowns: 6,
    Ptouchdowns: 42,
  },
  {
    team: "Bomb Squad",
    player: "Stephen",
    completions: 192,
    Ryards: 423,
    Pyards: 2498,
    picks: 17,
    Rtouchdowns: 6,
    Ptouchdowns: 44,
  },
  {
    team: "Bulls",
    player: "Redbull",
    completions: 194,
    Ryards: 661,
    Pyards: 2229,
    picks: 12,
    Rtouchdowns: 16,
    Ptouchdowns: 47,
  },
  {
    team: "Blue Ballers",
    player: "Danny Gonzo",
    completions: 68,
    Ryards: 278,
    Pyards: 809,
    picks: 2,
    Rtouchdowns: 3,
    Ptouchdowns: 16,
  },
  {
    team: "Redskins",
    player: "Sergio Rigau",
    completions: 16,
    Ryards: 27,
    Pyards: 405,
    picks: 1,
    Rtouchdowns: 1,
    Ptouchdowns: 8,
  },
];
