"use client";

export const qbStats = [
  {
    team: "Redskins",
    player: "Jonny",
    completions: 149,
    Ryards: 227,
    Pyards: 1712,
    picks: 15,
    Rtouchdowns: 4,
    Ptouchdowns: 33,
  },
  {
    team: "Miami Vice",
    player: "Nick Cupelli",
    completions: 124,
    Ryards: 247,
    Pyards: 1516,
    picks: 7,
    Rtouchdowns: 4,
    Ptouchdowns: 22,
  },
  {
    team: "Blue Ballers",
    player: "Nicky",
    completions: 137,
    Ryards: 155,
    Pyards: 1376,
    picks: 10,
    Rtouchdowns: 0,
    Ptouchdowns: 20,
  },
  {
    team: "The Clan",
    player: "Nick Dinicola",
    completions: 109,
    Ryards: 389,
    Pyards: 1237,
    picks: 5,
    Rtouchdowns: 5,
    Ptouchdowns: 23,
  },
  {
    team: "Bomb Squad",
    player: "Stephen",
    completions: 120,
    Ryards: 303,
    Pyards: 1614,
    picks: 12,
    Rtouchdowns: 6,
    Ptouchdowns: 26,
  },
  {
    team: "Bulls",
    player: "Redbull",
    completions: 125,
    Ryards: 413,
    Pyards: 1352,
    picks: 10,
    Rtouchdowns: 10,
    Ptouchdowns: 29,
  },
  {
    team: "Blue Ballers",
    player: "Danny Gonzo",
    completions: 25,
    Ryards: 65,
    Pyards: 292,
    picks: 0,
    Rtouchdowns: 0,
    Ptouchdowns: 7,
  },
  {
    team: "Redskins",
    player: "Sergio Rigau",
    completions: 4,
    Ryards: 0,
    Pyards: 66,
    picks: 0,
    Rtouchdowns: 0,
    Ptouchdowns: 2,
  },
];
